# Generated by Django 3.2.15 on 2022-10-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroapp', '0003_register_tb_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_tb',
            name='ADDRESS',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
