# Generated by Django 3.2.15 on 2022-10-18 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroapp', '0004_register_tb_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_tb',
            name='STATUS',
            field=models.CharField(default='1', max_length=255),
        ),
        migrations.AlterField(
            model_name='register_tb',
            name='ADDRESS',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
