# Generated by Django 3.2.15 on 2022-10-25 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroapp', '0005_auto_20221018_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRODUCT_NAME', models.CharField(max_length=255)),
                ('CATEGORY', models.CharField(max_length=255)),
                ('PRICE', models.CharField(max_length=255)),
                ('IMAGE', models.ImageField(upload_to='product/')),
            ],
        ),
    ]
