# Generated by Django 3.2.15 on 2022-10-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroapp', '0006_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='STATUS',
            field=models.CharField(default='1', max_length=255),
        ),
    ]
