# Generated by Django 3.2.15 on 2022-10-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroapp', '0007_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_tb',
            name='IMAGE',
            field=models.ImageField(default=2, upload_to='user/'),
            preserve_default=False,
        ),
    ]
