# Generated by Django 3.2.15 on 2022-11-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroapp', '0008_register_tb_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_tb',
            name='hashpass',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='register_tb',
            name='IMAGE',
            field=models.ImageField(blank=True, upload_to='user/'),
        ),
    ]
