# Generated by Django 3.2.15 on 2022-11-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroapp', '0009_auto_20221101_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRODUCT_DESCRIPTION',
            field=models.CharField(default='2', max_length=255),
        ),
    ]
