# Generated by Django 3.2.15 on 2022-11-04 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agroapp', '0011_alter_product_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TOTAL_PRICE', models.CharField(max_length=255)),
                ('STATUS', models.CharField(max_length=255)),
                ('PID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agroapp.product')),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agroapp.register_tb')),
            ],
        ),
    ]
