# Generated by Django 3.2.15 on 2022-11-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroapp', '0013_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='QUANTITY',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
