# Generated by Django 3.2.15 on 2022-11-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroapp', '0014_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='STATUS',
            field=models.CharField(default='pending', max_length=255),
        ),
    ]
